name: Deploy Network

name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Which cloud to deploy"
        type: choice
        options: [both]
        required: true
      environment:
        type: choice
        options: [qa]
        required: true
      action:
        type: choice
        options: [apply]
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cloud: ${{ 
          inputs.cloud == 'both'
          && fromJson('["aws","azure"]')
          || fromJson(format('["%s"]', inputs.cloud))
        }}

    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/terraform-reusable.yml
        with:
          cloud: ${{ matrix.cloud }}
          environment: ${{ inputs.environment }}
          action: ${{ inputs.action }}
        secrets: inherit