name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        options: [aws , azure]
        required: true
      environment:
        type: choice
        options: [qa, dev, prod]
        required: true
      action:
        type: choice
        options: [apply]
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      cloud: ${{ inputs.cloud }}
      environment: ${{ inputs.environment }}
      action: ${{ inputs.action }}