name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Which cloud to deploy"
        type: choice
        options: [both]
        required: true
      environment:
        type: choice
        options: [qa]
        required: true
      action:
        type: choice
        options: [apply]
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        cloud: >-
          ${{ inputs.cloud == 'both'
              && fromJson('["aws","azure"]')
              || fromJson(format('["%s"]', inputs.cloud))
          }}

    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      cloud: ${{ matrix.cloud }}
      environment: ${{ inputs.environment }}
      action: ${{ inputs.action }}