name: Reusable Terraform Network Workflow

on:
  workflow_call:
    inputs:
      cloud:
        required: true
        type: string
      environment:
        required: true
        type: string
      action:
        required: true
        type: string   
      public_subnet_count:
        required: true
        type: number
      private_subnet_count:
        required: true
        type: number
      subnet_newbits:
        required: true
        type: number  

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        if: inputs.cloud == 'azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export Azure vars for Terraform
        if: inputs.cloud == 'azure'
        run: |
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: AWS Login (OIDC)
        if: inputs.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      # -EXPORT SUBNET COUNTS TO TERRAFORM ----------
      - name: Export subnet counts
        run: |
          echo "TF_VAR_public_subnet_count=${{ inputs.public_subnet_count }}" >> $GITHUB_ENV
          echo "TF_VAR_private_subnet_count=${{ inputs.private_subnet_count }}" >> $GITHUB_ENV
          echo "TF_VAR_subnet_newbits=${{ inputs.subnet_newbits }}" >> $GITHUB_ENV
     
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ inputs.cloud == 'azure' && 'Azure' || 'AWS' }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.cloud == 'azure' && 'Azure' || 'AWS' }}

      - name: Terraform Plan
        if: inputs.action == 'apply'
        run: |
          terraform plan \
            -var-file=envs/${{ inputs.environment }}.tfvars \
            -out=tfplan
        working-directory: ${{ inputs.cloud == 'azure' && 'Azure' || 'AWS' }}

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ inputs.cloud == 'azure' && 'Azure' || 'AWS' }}

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file=envs/${{ inputs.environment }}.tfvars
        working-directory: ${{ inputs.cloud == 'azure' && 'Azure' || 'AWS' }}